# utils/co2_tracker.py
# CO2 emissions and savings calculations.
# No Streamlit imports — pure Python calculation.

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
CO2_PER_KWH_GRID   = 0.82   # kg CO2 emitted per kWh drawn from the Indian grid
CO2_PER_KWH_SOLAR  = 0.05   # kg CO2 per kWh for solar lifecycle emissions
KM_PER_KG_CO2      = 4.6    # km a petrol car drives per kg CO2 emitted (~120 g/km)


def calculate_co2(
    grid_reliance_kWh: float,
    solar_generation_kWh: float,
) -> dict:
    """
    Calculate CO2 emissions from grid usage and CO2 saved by solar.

    Parameters:
        grid_reliance_kWh    (float): kWh drawn from the grid today.
        solar_generation_kWh (float): kWh generated by solar panels today.

    Returns:
        dict with keys:
            grid_co2_kg        — CO2 emitted from grid usage today (kg)
            solar_co2_saved_kg — CO2 avoided by using solar instead of grid (kg)
            car_km_equivalent  — equivalent km driven by a petrol car
            net_co2_kg         — net CO2 impact today (grid − savings)
    """
    grid_co2       = round(grid_reliance_kWh * CO2_PER_KWH_GRID, 3)
    solar_co2_saved = round(
        solar_generation_kWh * (CO2_PER_KWH_GRID - CO2_PER_KWH_SOLAR), 3
    )
    car_km         = round(grid_co2 * KM_PER_KG_CO2, 1)
    net_co2        = round(max(0.0, grid_co2 - solar_co2_saved), 3)

    return {
        "grid_co2_kg":         grid_co2,
        "solar_co2_saved_kg":  solar_co2_saved,
        "car_km_equivalent":   car_km,
        "net_co2_kg":          net_co2,
    }
