# utils/energy_calculator.py
# Core energy prediction logic migrated from predict_energy_needs.py.
# No Streamlit imports — pure Python calculation.

# ---------------------------------------------------------------------------
# Module-level constants
# Base values assume a reference home: 1500 sq ft, 10 solar panels, 1 person.
# ---------------------------------------------------------------------------

# kWh generated by a 10-panel reference system under each weather condition
SOLAR_GENERATION_BASE = {
    "sunny":  7.0,   # kWh — near-peak output from a typical home solar system
    "cloudy": 2.5,   # kWh — diffuse light still generates some power
    "rainy":  0.8,   # kWh — minimal generation through heavy cloud cover
}

# kWh consumed by a 1500 sq ft home with 1 person under each weather condition
ENERGY_CONSUMPTION_BASE = {
    "sunny":  5.0,   # kWh — low lighting/heating needs
    "cloudy": 7.0,   # kWh — moderate extra lighting and heating
    "rainy":  9.0,   # kWh — high lighting, heating, and appliance use
}

REFERENCE_SQ_FT  = 1500   # sq ft — baseline home size
REFERENCE_PANELS = 10     # panels — baseline solar installation
PERSON_FACTOR    = 0.05   # each additional person adds 5% to consumption


def predict_energy_needs(
    weather_condition: str,
    home_sq_ft: float = REFERENCE_SQ_FT,
    num_panels: int   = REFERENCE_PANELS,
    num_members: int  = 1,
) -> dict:
    """
    Predicts energy generation, consumption, and grid reliance based on
    weather conditions and home-specific details.

    Parameters:
        weather_condition (str): One of "sunny", "cloudy", or "rainy".
        home_sq_ft (float):      Home size in square feet (default 1500).
        num_panels (int):        Number of solar panels installed (default 10).
        num_members (int):       Number of people in the household (default 1).

    Returns:
        dict with keys:
            weather_condition, solar_generation_kWh, consumption_kWh,
            grid_reliance_kWh, recommendation.

    Raises:
        ValueError: If weather_condition is unrecognised or numeric inputs
                    are out of valid range.
    """
    # --- Step 1: Validate ---
    weather = weather_condition.strip().lower()
    if weather not in SOLAR_GENERATION_BASE:
        raise ValueError(
            f"Unknown weather condition '{weather_condition}'. "
            "Please use 'sunny', 'cloudy', or 'rainy'."
        )
    if home_sq_ft <= 0:
        raise ValueError("Home size must be greater than 0 sq ft.")
    if num_panels < 0:
        raise ValueError("Number of solar panels cannot be negative.")
    if num_members < 1:
        raise ValueError("Number of family members must be at least 1.")

    # --- Step 2: Scale solar generation by panel count ---
    panel_scale = num_panels / REFERENCE_PANELS
    generation  = round(SOLAR_GENERATION_BASE[weather] * panel_scale, 2)

    # --- Step 3: Scale consumption by home size and occupancy ---
    size_scale   = home_sq_ft / REFERENCE_SQ_FT
    person_scale = 1.0 + PERSON_FACTOR * (num_members - 1)
    consumption  = round(ENERGY_CONSUMPTION_BASE[weather] * size_scale * person_scale, 2)

    # --- Step 4: Calculate grid reliance ---
    grid_reliance = round(max(0.0, consumption - generation), 2)

    # --- Step 5: Build recommendation ---
    moderate_threshold = round(consumption * 0.4, 2)

    if grid_reliance <= 0:
        recommendation = (
            "Your solar panels cover all energy needs today. "
            "Any surplus can charge a battery or be exported to the grid."
        )
    elif grid_reliance <= moderate_threshold:
        recommendation = (
            f"Solar covers most of your needs. You'll need about {grid_reliance:.1f} kWh "
            "from the grid — consider delaying high-energy tasks (e.g. dishwasher, "
            "washing machine) until a sunnier period."
        )
    else:
        recommendation = (
            f"Low solar output today. Expect to draw {grid_reliance:.1f} kWh from the grid. "
            "Try to minimise non-essential appliance use and check your battery reserves."
        )

    return {
        "weather_condition":    weather,
        "solar_generation_kWh": generation,
        "consumption_kWh":      consumption,
        "grid_reliance_kWh":    grid_reliance,
        "recommendation":       recommendation,
    }
