# utils/green_score.py
# Green Score calculation and badge assignment.
# No Streamlit imports — pure Python calculation.


def calculate_green_score(
    solar_generation_kWh: float,
    consumption_kWh: float,
) -> dict:
    """
    Calculate a Green Score (0–100) based on how much of the home's
    energy consumption is covered by solar generation.

    Score = (solar_generation / consumption) × 100, capped at 100.
    If consumption is 0 the score is 100 (nothing to power = perfect).

    Parameters:
        solar_generation_kWh (float): kWh generated by solar panels today.
        consumption_kWh      (float): kWh consumed by the household today.

    Returns:
        dict with keys:
            score   (int)   — 0–100
            badge   (str)   — emoji badge label
            message (str)   — encouraging plain-English message
    """
    if consumption_kWh <= 0:
        score = 100
    else:
        raw   = (solar_generation_kWh / consumption_kWh) * 100
        score = min(100, round(raw))

    if score >= 80:
        badge   = "🌟 Eco Champion"
        message = (
            f"Outstanding! Your solar panels cover {score}% of your energy needs. "
            "You're making a real difference for the planet — keep it up!"
        )
    elif score >= 50:
        badge   = "🌿 Green Achiever"
        message = (
            f"Great work! Solar covers {score}% of your consumption. "
            "A few more panels or small efficiency tweaks could push you into Eco Champion territory."
        )
    else:
        badge   = "🌱 Getting Started"
        message = (
            f"You're on your way! Solar covers {score}% of your energy today. "
            "Consider adding more panels or shifting heavy appliance use to sunny hours to boost your score."
        )

    return {
        "score":   score,
        "badge":   badge,
        "message": message,
    }
